---
name: Build Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v6

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'

    - name: Dependencies
      run: go mod download

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: go build -v -o "dist/xtream-api-${{ matrix.goos }}-${{ matrix.goarch }}" ./...

    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: xtream-api-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/*
