---
name: Build Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'

    - name: Fetch Dependencies
      run: go mod download

    - name: Build Artifacts
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        BINARY_NAME="xtream-api"
        BINARY_NAME+="-${{ matrix.goos }}-${{ matrix.goarch }}"

        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME+=".exe"
        fi

        LDFLAGS="-X main.Branch=$(git branch --show-current)"

        go build -v -ldflags="${LDFLAGS}" -o "build/${BINARY_NAME}" .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: xtream-api-${{ matrix.goos }}-${{ matrix.goarch }}
        path: build/*
